### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Seanny123** [AndreaCensi/env_dvs#2]
Here is a list of missing dependencies that I installed after trying to run the program threw a few interesting errors.

```
python-cjson
python-virtualenv
scipy
```

I don't know what the best way is to resolve these dependencies. Usually I just see them included in the README, so I'll add them if you think that's the best idea. It really wasn't any trouble for me to install them, but doing them all in one shot would have been easier. I'm mentioning this so that maybe it will help you make other code you share easier to run, but feel free to ignore this report.

**Comment by AndreaCensi** [comment]
Thanks Sean, I will add these comments to the README. (These are systems dependencies, so specific to Linux / Ubuntu (or Debian), so they cannot be declared in the Python package, which is, in theory, multi-platform.)
